name: yesareem_website
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  carousel_slider: ^4.2.1
  marquee: ^2.2.3
  google_fonts: ^6.1.0
  expandable_search_bar: ^0.0.2
  http: ^1.1.0
  flutter_rating_stars: ^1.0.3+4
  flutter_svg:
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/

fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/Outfit-Thin.ttf
        weight: 100
      - asset: assets/fonts/Outfit-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Outfit-Light.ttf
        weight: 300
      - asset: assets/fonts/Outfit-Regular.ttf
        weight: 400
      - asset: assets/fonts/Outfit-Medium.ttf
        weight: 500
      - asset: assets/fonts/Outfit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Outfit-Bold.ttf
        weight: 700
      - asset: assets/fonts/Outfit-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Outfit-Black.ttf
        weight: 900
